import { chromium } from 'playwright';
const b = await chromium.launch({ headless:true, executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe' });
const errs=[];
const p = await b.newPage({ viewport:{width:390,height:844} }); p.on('pageerror',e=>errs.push(e.message));
await p.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
await p.evaluate(()=>localStorage.setItem('mb-cookie-consent','rejected')); await p.reload({waitUntil:'networkidle'});
const msgs = () => p.evaluate(()=>[...document.querySelectorAll('#formulario-captacion .hero-field-error')].map(e=>e.textContent));
// tab through empty fields: no errors yet
await p.locator('#hero-name').focus(); await p.keyboard.press('Tab'); await p.keyboard.press('Tab');
console.log('tab through empty:', JSON.stringify(await msgs()));
await p.locator('#hero-phone').pressSequentially('55ab12'); await p.locator('#hero-name').focus();
console.log('phone value:', await p.locator('#hero-phone').inputValue(), JSON.stringify(await msgs()));
await p.locator('#hero-phone').pressSequentially('345678'); 
console.log('phone after typing more:', await p.locator('#hero-phone').inputValue(), JSON.stringify(await msgs()));
await p.locator('#hero-phone').pressSequentially('99');
console.log('phone max:', await p.locator('#hero-phone').inputValue());
await p.locator('#hero-name').fill('123'); await p.locator('#hero-phone').focus();
console.log('bad name:', JSON.stringify(await msgs()));
await p.locator('#hero-name').fill('Ana'); 
console.log('fixed name live:', JSON.stringify(await msgs()));
await p.getByRole('button',{name:/Continuar con mi caso/}).click(); await p.waitForTimeout(250);
console.log('submit:', JSON.stringify(await msgs()), 'fieldset error class:', await p.locator('.hero-situation-fieldset').evaluate(e=>e.classList.contains('has-error')), 'chip border:', await p.locator('.situation-chip').first().evaluate(e=>getComputedStyle(e).borderColor));
await p.locator('#formulario-captacion').screenshot({path:'C:/Users/Amauri/AppData/Local/Temp/claude/D--t2o-carpet-especial-mejora-tu-buro-mejora-tu-buro/07e66327-91f7-4a14-ba0e-0b6b83073b6e/scratchpad/valid-errors.png'});
await p.locator('.situation-chip',{hasText:'Carta convenio'}).click(); await p.locator('#hero-privacy').check();
console.log('after fixing:', JSON.stringify(await msgs()));
await p.getByRole('button',{name:/Continuar con mi caso/}).click();
await p.getByRole('dialog').waitFor();
console.log('modal contact:', await p.getByRole('dialog').innerText().then(t=>t.match(/Contacto:[^\n]*/)[0]));
console.log('errors', JSON.stringify(errs)); await b.close();
