import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true, executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 });
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
await page.screenshot({path:'.pptx-work/mobile-hero.png',fullPage:false});
await page.locator('#hero-situation-select').selectOption('atrasos');
await page.getByLabel('Nombre',{exact:true}).fill('Prueba UX');
await page.getByLabel('Celular').fill('5512345678');
await page.getByLabel(/Correo electrónico/).fill('prueba@example.com');
await page.getByRole('checkbox',{name:/He leído y acepto/}).check();
await page.getByRole('button',{name:/Continuar con mi caso/}).click();
await page.getByRole('dialog').waitFor();
await page.getByText('Prueba UX · 5512345678').waitFor();
await page.screenshot({path:'.pptx-work/mobile-step2.png',fullPage:false});
if(errors.length) throw new Error(errors.join('\n'));
console.log(JSON.stringify({mobileViewport:page.viewportSize(),heroHeight:await page.locator('#hero').evaluate(el=>Math.round(el.getBoundingClientRect().height)),formCard:await page.locator('.hero-intake-card').boundingBox(),cta:await page.getByRole('button',{name:/Continuar con mi caso/}).boundingBox(),cookie:await page.locator('.cookie-banner').boundingBox(),ctaVisible:await page.getByRole('button',{name:/Continuar con mi caso/}).isVisible(),dialogOpens:true,consoleErrors:errors},null,2));
const desktop=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
await desktop.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
await desktop.screenshot({path:'.pptx-work/desktop-hero.png'});
const desktopCta=await desktop.getByRole('button',{name:/Continuar con mi caso/}).boundingBox();
await desktop.getByRole('link',{name:'Revisar mi caso'}).click();
const anchorResult={url:desktop.url(),focused:await desktop.evaluate(()=>document.activeElement?.tagName+' '+document.activeElement?.getAttribute('role'))};
if(!anchorResult.url.includes('#formulario-captacion')) throw new Error('Header CTA did not navigate to the in-hero form anchor.');
console.log(JSON.stringify({desktopViewport:desktop.viewportSize(),heroHeight:await desktop.locator('#hero').evaluate(el=>Math.round(el.getBoundingClientRect().height)),formCard:await desktop.locator('.hero-intake-card').boundingBox(),cta:desktopCta,cookie:await desktop.locator('.cookie-banner').boundingBox(),anchorResult},null,2));
await browser.close();
